### ISSUE TITLE
No Validation Button in Chapter- 3, 4, 9, 17

### ISSUE THREAD

**Issue by mrrifat** [learn-ocean/ocean-academy#71] opened 2021-03-16 07:50 UTC
I am unable to validate my answer. There is only the next chapter button. 
![ocean](https://user-images.githubusercontent.com/25559246/111273799-7309c500-865e-11eb-8b37-01e996388cce.jpg)

**Comment by moritzkirstein** [comment] 2021-03-28 12:04
Just leaving some feedback here: this seems to be related to the screen resolution. On questions with the code-editor the validation button gets cropped out and can't be scrolled to
Resolution to reproduce: 1280x720

**Comment by MeMent0L** [comment] 2022-06-17 14:54
This was fixed long ago, closing the issue here.

**Closed by MeMent0L** 2022-06-17 14:54 UTC
Labels: bug, good first issue
